export const GET_HOTEL_PRICE = "GET_HOTEL_PRICE";
export const GET_HOTEL_PRICE_SUCCESS = "GET_HOTEL_PRICE_SUCCESS";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const SORT_BY_STARS = "SORT_BY_STARS";
